#!/usr/bin/env python3

#         Python Stream Deck Library
#      Released under the MIT license
#
#   dean [at] fourwalledcubicle [dot] com
#         www.fourwalledcubicle.com
#

# Example script showing one way to display animated images using the
# library, by pre-rendering all the animation frames into the StreamDeck
# device's native image format, and displaying them with a periodic
# timer.

import itertools
import os
import threading
import time
import atexit
import signal

from fractions import Fraction
from PIL import Image, ImageDraw, ImageFont, ImageSequence
from StreamDeck.DeviceManager import DeviceManager
from StreamDeck.ImageHelpers import PILHelper
from StreamDeck.Transport.Transport import TransportError

# Folder location of image assets used by this example.
# ASSETS_PATH = os.path.join(os.path.dirname(__file__), "Assets")
ASSETS_PATH = os.path.join("/usr/local/share/pcar", "Assets")
# Animation frames per second to attempt to display on the StreamDeck devices.
FRAMES_PER_SECOND = 2
FONT = ImageFont.truetype(os.path.join(ASSETS_PATH, "Anonymous.ttf"), 14)

BUTTON_NO = 6
ALL_BUTTON = 2
NORMAL_BUTTONS = [1, 3, 4, 5, 6]

class Button:
    state = 0
    alert = 0
    image = itertools.cycle([1])

buttons = {
        1: Button(),
        2: Button(),
        3: Button(),
        4: Button(),
        5: Button(),
        6: Button(),
}

BUTTON_TO_SENSOR = {
        1: 1,
        2: "all",
        3: 5,
        4: 2,
        5: 3,
        6: 4
}
SENSOR_TO_BUTTON = {
        1: 1,
        2: 4,
        3: 5,
        4: 6,
        5: 3,
}

animations = {
        "off": dict(),
        "on": dict(),
        "alert": dict(),
}

def turn_on(button):
    buttons[button].state = 1
    print("Button {} turned ON".format(button))
    os.system("pcar outwr {} 1".format(BUTTON_TO_SENSOR[button]))
    # TODO CHECK FOR ERROR
    if not buttons[button].alert:
        buttons[button].image = itertools.cycle(animations["on"][button])

def turn_off(button):
    buttons[button].state = 0
    print("Button {} turned OFF".format(button))
    os.system("pcar outwr {} 0".format(BUTTON_TO_SENSOR[button]))
    if not buttons[button].alert:
        buttons[button].image = itertools.cycle(animations["off"][button])

# Loads in a source image, extracts out the individual animation frames (if
# any) and returns a list of animation frames in the StreamDeck device's
# native image format.
def create_animation_frames(deck, image_filename, label_text):
    icon_frames = list()

    # Open the source image asset.
    icon = Image.open(os.path.join(ASSETS_PATH, image_filename))

    # Iterate through each animation frame of the source image
    for frame in ImageSequence.Iterator(icon):
        # Create new key image of the correct dimensions, black background.
        frame_image = PILHelper.create_scaled_image(deck, frame)
        draw = ImageDraw.Draw(frame_image)
        draw.text((frame_image.width / 2, frame_image.height / 2 - 5),
                  text=label_text, font=FONT, anchor="ms", fill="white", align="center")

        # Pre-convert the generated image to the native format of the StreamDeck
        # so we don't need to keep converting it when showing it on the device.
        native_frame_image = PILHelper.to_native_format(deck, frame_image)

        # Store the rendered animation frame for later user.
        icon_frames.append(native_frame_image)

    # Return the decoded list of frames - the caller will need to decide how to
    # sequence them for display.
    return icon_frames


# Closes the StreamDeck device on key state change.
def key_change_callback(deck, key, state):
    # Use a scoped-with on the deck to ensure we're the only thread using it
    # right now.
    if not state:
        return
    button = key + 1
    if button == ALL_BUTTON:
        if buttons[button].state == 0:
            buttons[button].state = 1
            buttons[button].image = itertools.cycle(animations["on"][button])
            for button in NORMAL_BUTTONS:
                turn_on(button)
        else:
            buttons[button].state = 0
            buttons[button].image = itertools.cycle(animations["off"][button])
            for button in NORMAL_BUTTONS:
                turn_off(button)
        return
    if buttons[button].state == 0:
        turn_on(button)
        # Check if all buttons are on
        sum_states = 0
        for button in NORMAL_BUTTONS:
            sum_states += int(buttons[button].state)
        if sum_states == len(NORMAL_BUTTONS):
            buttons[ALL_BUTTON].state = 1
            buttons[ALL_BUTTON].image = itertools.cycle(animations["on"][ALL_BUTTON])
    else:
        turn_off(button)
        # Check if all buttons are off
        if buttons[ALL_BUTTON].state == 1:
            buttons[ALL_BUTTON].state = 0
            buttons[ALL_BUTTON].image = itertools.cycle(animations["off"][ALL_BUTTON])


prev_sensor_state = {
        1: 0,
        2: 0,
        3: 0,
        4: 0,
        5: 0,
}

def check_sensors():
    sensor_mask = os.popen("pcar inrd").read()
    sensor_mask = int(sensor_mask)
    for sensor in range(1, 6, 1):
        state = sensor_mask & (1 << (sensor - 1))
        state = int(state != 0)
        if state == prev_sensor_state[sensor]:
            continue
        prev_sensor_state[sensor] = state;
        button = SENSOR_TO_BUTTON[sensor]
        if state:
            buttons[button].image = itertools.cycle(animations["alert"][button])
            # TODO: Activate siren and piezo buzzer
        elif not state:
            if buttons[button].state == 1:
                buttons[button].image = itertools.cycle(animations["on"][button])
            else:
                buttons[button].image = itertools.cycle(animations["off"][button])
            # TODO: Stop siren and piezo buzzer

def t_check_sensors(deck):
        while deck.is_open():
            try:
                check_sensors()
            except TransportError as err:
                print("Transport error {}".format(err))
                break

def _cleanup(deck):
    with deck:
        os.system("pcar outwr 0")
        deck.reset()
        deck.close()

def my_wrapped_sigterm_handler(deck):
    def signal_handler(signum, frame): # the actual sigint handler
        _cleanup(deck)
    return signal_handler

if __name__ == "__main__":
    streamdecks = DeviceManager().enumerate()

    print("Found {} Stream Deck(s).\n".format(len(streamdecks)))

    for index, deck in enumerate(streamdecks):
        # This example only works with devices that have screens.
        if not deck.is_visual():
            continue

        signal.signal(signal.SIGTERM, my_wrapped_sigterm_handler(deck))

        deck.open()
        deck.reset()

        atexit.register(_cleanup, deck)

        print("Opened '{}' device (serial number: '{}')".format(deck.deck_type(), deck.get_serial_number()))

        # Set initial screen brightness to 30%.
        deck.set_brightness(30)

        # Pre-render a list of animation frames for each source image, in the
        # native display format so that they can be quickly sent to the device.
        print("Loading animations...")
        animations["off"] = {
            1: create_animation_frames(deck, "black_bg.jpg", "Front\nLeft"),
            2: create_animation_frames(deck, "black_bg.jpg", "Activate\nAll"),
            3: create_animation_frames(deck, "black_bg.jpg", "Front\nRight"),
            4: create_animation_frames(deck, "black_bg.jpg", "Rear\nLeft"),
            5: create_animation_frames(deck, "black_bg.jpg", "Rear\nCenter"),
            6: create_animation_frames(deck, "black_bg.jpg", "Rear\nRight"),
        }
        animations["on"] = {
            1: create_animation_frames(deck, "green_bg.jpg", "Front\nLeft"),
            2: create_animation_frames(deck, "green_bg.jpg", "Stop\nAll"),
            3: create_animation_frames(deck, "green_bg.jpg", "Front\nRight"),
            4: create_animation_frames(deck, "green_bg.jpg", "Rear\nLeft"),
            5: create_animation_frames(deck, "green_bg.jpg", "Rear\nCenter"),
            6: create_animation_frames(deck, "green_bg.jpg", "Rear\nRight"),
        }
        animations["alert"] = {
            1: create_animation_frames(deck, "flashing_red_bg.gif", "Front\nLeft"),
            2: create_animation_frames(deck, "green_bg.jpg", "Activate\nAll"),
            3: create_animation_frames(deck, "flashing_red_bg.gif", "Front\nRight"),
            4: create_animation_frames(deck, "flashing_red_bg.gif", "Rear\nLeft"),
            5: create_animation_frames(deck, "flashing_red_bg.gif", "Rear\nCenter"),
            6: create_animation_frames(deck, "flashing_red_bg.gif", "Rear\nRight"),
        }
        print("Ready.")

        # Create a mapping of StreamDeck keys to animation image sets that will
        # be displayed.
        for k in range(deck.key_count()):
            b = k + 1
            # Each key gets an infinite cycle generator bound to the animation
            # frames, so it will loop the animated sequence forever.
            buttons[b].image = itertools.cycle(animations["off"][b])
        #key_images[0] = itertools.cycle(animations[0]);

        # Helper function that will run a periodic loop which updates the
        # images on each key.
        def animate(fps):
            # Convert frames per second to frame time in seconds.
            #
            # Frame time often cannot be fully expressed by a float type,
            # meaning that we have to use fractions.
            frame_time = Fraction(1, fps)

            # Get a starting absolute time reference point.
            #
            # We need to use an absolute time clock, instead of relative sleeps
            # with a constant value, to avoid drifting.
            #
            # Drifting comes from an overhead of scheduling the sleep itself -
            # it takes some small amount of time for `time.sleep()` to execute.
            next_frame = Fraction(time.monotonic())

            # Periodic loop that will render every frame at the set FPS until
            # the StreamDeck device we're using is closed.
            while deck.is_open():
                try:
                    # Use a scoped-with on the deck to ensure we're the only
                    # thread using it right now.
                    with deck:
                        # Update the key images with the next animation frame.
                        for key in range(BUTTON_NO):
                            deck.set_key_image(key, next(buttons[key + 1].image))
                except TransportError as err:
                    print("TransportError: {0}".format(err))
                    # Something went wrong while communicating with the device
                    # (closed?) - don't re-schedule the next animation frame.
                    break

                # Set the next frame absolute time reference point.
                #
                # We are running at the fixed `fps`, so this is as simple as
                # adding the frame time we calculated earlier.
                next_frame += frame_time

                # Knowing the start of the next frame, we can calculate how long
                # we have to sleep until its start.
                sleep_interval = float(next_frame) - time.monotonic()

                # Schedule the next periodic frame update.
                #
                # `sleep_interval` can be a negative number when current FPS
                # setting is too high for the combination of host and
                # StreamDeck to handle. If this is the case, we skip sleeping
                # immediately render the next frame to try to catch up.
                if sleep_interval >= 0:
                    time.sleep(sleep_interval)

        # Kick off the key image animating thread.
        threading.Thread(target=animate, args=[FRAMES_PER_SECOND]).start()
        threading.Thread(target=t_check_sensors, args=[deck]).start()

        # Register callback function for when a key state changes.
        deck.set_key_callback(key_change_callback)

        # Wait until all application threads have terminated (for this example,
        # this is when all deck handles are closed).
        for t in threading.enumerate():
            try:
                t.join()
            except RuntimeError:
                pass
